version: '3.9'

services:
  db:
    image: postgres:15
    ...

  web:
    build:
      context: .
    ports:
      - "3002:3002"
    ...

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    